version: "3"
services:
  naturewatchcameraserver:
    container_name: naturewatchcameraserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - "/home/pi/data:/naturewatch_camera_server/static/data"
    devices:
      - "/dev/vcsm"
      - "/dev/vchiq"

